/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandsignup;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author ACER
 */
public class AddAssets extends javax.swing.JFrame {

    /**
     * Creates new form AddAssets
     */
    public AddAssets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        assid = new javax.swing.JTextField();
        asstype = new javax.swing.JComboBox<>();
        srnum = new javax.swing.JTextField();
        descr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Assets Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Assets Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Serial No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 204, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("Description");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        assid.setBackground(new java.awt.Color(255, 255, 204));
        assid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        assid.setPreferredSize(new java.awt.Dimension(400, 40));
        getContentPane().add(assid, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 49, 409, 44));

        asstype.setBackground(new java.awt.Color(255, 255, 204));
        asstype.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        asstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Printer", "Mouse", "Keyboard", "Headphone", " " }));
        asstype.setPreferredSize(new java.awt.Dimension(400, 40));
        getContentPane().add(asstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 142, -1, -1));

        srnum.setBackground(new java.awt.Color(255, 255, 204));
        srnum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        srnum.setPreferredSize(new java.awt.Dimension(400, 40));
        getContentPane().add(srnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 235, 409, 44));

        descr.setBackground(new java.awt.Color(255, 255, 204));
        descr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descr.setPreferredSize(new java.awt.Dimension(400, 40));
        descr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descrActionPerformed(evt);
            }
        });
        getContentPane().add(descr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 409, 47));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 502, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 80, 30));

        jTable1.setBackground(new java.awt.Color(153, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 0, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Assets Id", "Assets Type", "Serial No.", "Status", "Description"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 18, 710, 460));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 0));
        jButton3.setText("Veiw");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 70, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginandsignup/MECON1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descrActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Home().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:  
    String assetId, assetType, serialNumber, description = "", query;
String SUrl = "jdbc:MySQL://localhost:3306/user";
String SUser = "root";
String SPass = "1234Anmol@";

try {
    // Load MySQL JDBC Driver
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
    Statement st = con.createStatement();

    // Validate mandatory fields
    if (assid.getText().isEmpty()) {
        JOptionPane.showMessageDialog(new JFrame(), "Asset ID is required", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (asstype.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(new JFrame(), "Asset Type is required", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (srnum.getText().isEmpty()) {
        JOptionPane.showMessageDialog(new JFrame(), "Serial Number is required", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        // Assign field values
        assetId = assid.getText();
        assetType = asstype.getSelectedItem().toString();
        serialNumber = srnum.getText();

        // Set description only if provided
        if (!descr.getText().isEmpty()) {
            description = descr.getText();
        }

        // Set status to "Available"
        String status = "Available";

        // Construct SQL query
        query = "INSERT INTO asset(asset_id, asset_type, sr_number, status, description) " +
                "VALUES('" + assetId + "', '" + assetType + "', '" + serialNumber + "', '" + status + "', '" + description + "')";

        // Execute the query
        st.execute(query);

        // Reset fields
        assid.setText("");
        asstype.setSelectedIndex(-1);
        srnum.setText("");
        descr.setText("");

        // Show success message
        JOptionPane.showMessageDialog(null, "Asset has been added successfully!");
    }
} catch (Exception e) {
    System.out.println("Error!" + e.getMessage());
    JOptionPane.showMessageDialog(new JFrame(), "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String SUrl = "jdbc:MySQL://localhost:3306/user";
    String SUser = "root";
    String SPass = "1234Anmol@";

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
        Statement st = con.createStatement();

        // Query only 'Available' or 'Returned' assets
        String query = "SELECT asset_id, asset_type, sr_number, status, description FROM asset WHERE status IN ('Available', 'Returned')";
        ResultSet rs = st.executeQuery(query);

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        while (rs.next()) {
            String id = rs.getString("asset_id");
            String type = rs.getString("asset_type");
            String serial = rs.getString("sr_number");
            String status = rs.getString("status");
            String description = rs.getString("description");

            model.addRow(new Object[]{id, type, serial, status, description});
        }

        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(new JFrame(), "Error loading asset table: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAssets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAssets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAssets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAssets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAssets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assid;
    private javax.swing.JComboBox<String> asstype;
    private javax.swing.JTextField descr;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField srnum;
    // End of variables declaration//GEN-END:variables
}
